debug: false
exp_name: "exp001"
model_name: "tf_efficientnetv2_s_in21k"
device_id: 0
batch_size: 32
img_size: 512
n_workers: 12
n_epochs: 40
start_epoch: 1
transform: true

initial_lr: 5e-4
final_lr: 1e-6

load_checkpoint:
  - ""
  - ""
  - ""
  - ""
  - ""

hold_out:
  - 0
  - 1
  - 2
  - 3
  - 4

df_train_path: "/workspace/data/df_train_study_level_npy640.csv"

accumulation_steps: 1
early_stopping_steps: 8
freeze_bn: false

fold_name: 'cv'

clahe: false
mix: false

use_amp: true
use_npy: true