debug: false
# exp_name: "exp003"
# exp_name: "exp011"
# exp_name: "exp026"
# exp_name: "exp030"
# exp_name: "exp204"
# exp_name: "exp205"
# exp_name: "exp206"
exp_name: "exp207"
model_name: "tf_efficientnet_b7_ns"
device_id: 0
batch_size: 8
img_size: 512
n_workers: 20
n_epochs: 30
start_epoch: 1
transform: true

initial_lr: 1e-4
final_lr: 1e-5

load_checkpoint:
  - "/workspace/output/exp206/model/cv0_weight_checkpoint_best.pth"
  - "/workspace/output/exp206/model/cv1_weight_checkpoint_best.pth"
  - "/workspace/output/exp206/model/cv2_weight_checkpoint_best.pth"
  - "/workspace/output/exp206/model/cv3_weight_checkpoint_best.pth"
  - "/workspace/output/exp206/model/cv4_weight_checkpoint_best.pth"

hold_out:
  - 0
  - 1
  - 2
  - 3
  - 4

df_train_path: "/workspace/data/df_train_study_level_npy640_2.csv"

accumulation_steps: 8
early_stopping_steps: 6
freeze_bn: true

fold_name: 'cv'

clahe: false
mix: false

use_amp: true
use_npy: true