#FROM pytorch/pytorch:latest
FROM pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y git tmux libopencv-dev

RUN pip install tensorboard opencv-python
RUN conda install -y jupyter jupyterlab
RUN conda install -y pandas scikit-learn matplotlib seaborn
RUN pip install albumentations==0.5.2
RUN pip install segmentation-models-pytorch==0.1.3
RUN pip install timm==0.4.9
RUN pip install pytorch-gradcam==0.2.1
RUN pip install pydicom==2.1.2 pylibjpeg==1.3.0 pylibjpeg-libjpeg==1.2.0
RUN pip install numpy==1.20.0
RUN pip install neptune-client==0.9.16
RUN pip install iterative-stratification==0.1.6
RUN pip install wandb==0.10.31
RUN pip install pycocotools==2.0.2 omegaconf==2.1.0
RUN pip install effdet==0.2.4 ensemble-boxes==1.0.6 fastcore==1.3.20 pytorch-lightning==1.3.5
RUN pip install git+https://github.com/alexhock/object-detection-metrics