debug: false
# exp_name: "exp003"
# exp_name: "exp013"
exp_name: "exp019"
model_name: "ecaresnet50t"
device_id: 0
batch_size: 16
img_size: 640
n_workers: 12
n_epochs: 20
start_epoch: 1
transform: true

initial_lr: 1e-4
final_lr: 1e-6

load_checkpoint:
  - "/workspace/output/exp013/model/cv0_weight_checkpoint_best.pth"
  - ""
  - ""
  - ""
  - ""

hold_out:
  - 0
  # - 1
  # - 2
  # - 3
  # - 4

df_train_path: "/workspace/data/df_train_study_level_npy640.csv"

accumulation_steps: 1
early_stopping_steps: 15
freeze_bn: false

fold_name: 'cv'

clahe: false
mix: false

use_amp: true
use_npy: true