debug: false
# exp_name: "exp003"
# exp_name: "exp011"
exp_name: "exp024"
model_name: "tf_efficientnet_b2_ns"
device_id: 0
batch_size: 32
img_size: 512
n_workers: 20
n_epochs: 50
start_epoch: 1
transform: true

initial_lr: 1e-4
final_lr: 1e-5

load_checkpoint:
  - ""
  - ""
  - ""
  - ""
  - ""

hold_out:
  - 0
  # - 1
  # - 2
  # - 3
  # - 4

df_train_path: "/workspace/data/df_train_study_level_npy640_2.csv"

accumulation_steps: 1
early_stopping_steps: 15
freeze_bn: true

fold_name: 'cv'

clahe: false
mix: false

use_amp: true
use_npy: true