debug: false
exp_name: "seg_exp001"
model_name: "efficientnet-b0"
# model_name: "tf_efficientnet_b2_ns"
device_id: 0
batch_size: 16
img_size: 512
n_workers: 20
n_epochs: 12
start_epoch: 1
transform: true

initial_lr: 1e-4
final_lr: 1e-5

load_checkpoint:
  - ""
  - ""
  - ""
  - ""
  - ""

hold_out:
  - 0
  # - 1
  # - 2
  # - 3
  # - 4

df_train_path: "/workspace/data/df_ranzcr_seg.csv"

accumulation_steps: 1
early_stopping_steps: 5
freeze_bn: false

fold_name: 'cv'

clahe: false
mix: false

use_amp: true
use_npy: true

use_bbox: true